name: msgpack
description: MsgPack for Dart
version: 0.9.0
authors:
- Kenneth Endfinger <kaendfinger@gmail.com>
- Dan Ellis <dan@danellis.me>
homepage: https://github.com/DirectMyFile/msgpack.dart
environment:
  sdk: "<3.0.0"
dev_dependencies:
  test: "^0.12.0"
